namespace WinPieGestures.ArtStyles;

/// <summary>Resolve on use, so the studio and draft labels also change language without losing edits.</summary>
public static class ArtStyleText
{
    private static readonly Dictionary<string, LocalizedString> Strings = new()
    {
        ["Title"] = new("主题工作室", "主題工作室", "Theme studio", "テーマスタジオ"),
        ["Description"] = new("选择一套风格，再把它变成你的。", "選擇一套風格，再把它變成你的。", "Choose a style. Make it yours.", "スタイルを選んで、自分らしく。"),
        ["paper"] = new("纸感极简", "紙感極簡", "Paper", "ペーパー"),
        ["obsidian"] = new("曜石科技", "曜石科技", "Obsidian", "オブシディアン"),
        ["grove"] = new("森林柔和", "森林柔和", "Grove", "グローブ"),
        ["glacier"] = new("冰川玻璃", "冰川玻璃", "Glacier", "グレイシャー"),
        ["pixel"] = new("复古像素", "復古像素", "Pixel", "ピクセル"),
        ["paper.Desc"] = new("暖纸 · 细线 · 留白", "暖紙 · 細線 · 留白", "Warm paper · Fine lines", "暖かい紙・細い線"),
        ["obsidian.Desc"] = new("深空 · 青绿 · 轨道", "深空 · 青綠 · 軌道", "Deep space · Mint · Orbits", "深宇宙・ミント・軌道"),
        ["grove.Desc"] = new("鼠尾草 · 哑光 · 柔圆", "鼠尾草 · 霧面 · 柔圓", "Sage · Matte · Soft edges", "セージ・マット・柔らかな角"),
        ["glacier.Desc"] = new("冰蓝 · 透光 · 层次", "冰藍 · 透光 · 層次", "Ice blue · Translucence", "アイスブルー・透明感"),
        ["pixel.Desc"] = new("方角 · 硬影 · 点阵", "方角 · 硬影 · 點陣", "Square edges · Hard shadows", "角ばった形・硬い影"),
        ["Custom"] = new("自定义主题", "自訂主題", "Custom theme", "カスタムテーマ"),
        ["Active"] = new("使用中", "使用中", "Active", "使用中"),
        ["Current"] = new("当前", "目前", "Current", "現在"),
        ["Legacy"] = new("基础主题", "基礎主題", "Base theme", "基本テーマ"),
        ["Apply"] = new("应用风格", "套用風格", "Apply style", "スタイルを適用"),
        ["CopyEdit"] = new("复制并编辑", "複製並編輯", "Copy & edit", "複製して編集"),
        ["Edit"] = new("编辑", "編輯", "Edit", "編集"),
        ["New"] = new("新建", "新增", "New", "新規"),
        ["Rename"] = new("重命名", "重新命名", "Rename", "名前を変更"),
        ["Delete"] = new("删除", "刪除", "Delete", "削除"),
        ["Import"] = new("导入", "匯入", "Import", "インポート"),
        ["Export"] = new("导出", "匯出", "Export", "エクスポート"),
        ["Follow"] = new("轮盘跟随整体风格", "輪盤跟隨整體風格", "Use this style for the wheel", "ホイールも同じスタイルにする"),
        ["FollowHint"] = new("独立二级配色与每扇区覆盖仍然优先。取消后可使用下方原有配色设置。", "獨立二級配色與每扇區覆寫仍然優先。取消後可使用下方原有配色設定。", "Independent secondary palettes and per-sector overrides take priority. Turn off to use the original wheel settings below.", "独立したサブホイール配色とセクター設定を優先します。オフにすると下の従来設定を使用できます。"),
        ["Name"] = new("主题名称", "主題名稱", "Theme name", "テーマ名"),
        ["NewName"] = new("我的主题", "我的主題", "My theme", "マイテーマ"),
        ["CopySuffix"] = new(" · 我的版本", " · 我的版本", " · My version", " · マイバージョン"),
        ["Editor"] = new("定制你的风格", "自訂你的風格", "Make it your own", "自分らしくカスタマイズ"),
        ["DraftHint"] = new("正在编辑草稿，保存前不会改变当前主题。", "正在編輯草稿，儲存前不會變更目前主題。", "Editing a draft. Your current theme stays unchanged until you save.", "下書きを編集中です。保存するまで現在のテーマは変わりません。"),
        ["Save"] = new("保存并应用", "儲存並套用", "Save & apply", "保存して適用"),
        ["Cancel"] = new("取消", "取消", "Cancel", "キャンセル"),
        ["Reset"] = new("撤销本次修改", "復原本次修改", "Reset edits", "変更をリセット"),
        ["Advanced"] = new("进阶：字体、线条与材质", "進階：字型、線條與材質", "Advanced: type, lines & material", "詳細：書体・線・質感"),
        ["FontFamily"] = new("字体", "字型", "Font family", "フォント"),
        ["IsDark"] = new("深色基底（标题栏与托盘）", "深色基底（標題列與系統匣）", "Dark base (title bar & tray)", "ダーク基調（タイトルバーとトレイ）"),
        ["Decoration"] = new("装饰风格", "裝飾風格", "Decoration style", "装飾スタイル"),
        ["CornerRadius"] = new("圆角", "圓角", "Corner radius", "角の丸み"),
        ["StrokeWidth"] = new("描边粗细", "描邊粗細", "Stroke width", "線の太さ"),
        ["ShadowBlur"] = new("阴影柔和度", "陰影柔和度", "Shadow softness", "影の柔らかさ"),
        ["ShadowDepth"] = new("阴影位移", "陰影位移", "Shadow depth", "影の距離"),
        ["ShadowOpacity"] = new("阴影强度", "陰影強度", "Shadow opacity", "影の濃さ"),
        ["WheelOpacity"] = new("轮盘不透明度", "輪盤不透明度", "Wheel opacity", "ホイールの不透明度"),
        ["DecorationStrength"] = new("装饰强度", "裝飾強度", "Decoration strength", "装飾の強さ"),
        ["Color.Background"] = new("界面背景", "介面背景", "Background", "背景"),
        ["Color.Surface"] = new("卡片与输入框", "卡片與輸入框", "Cards & inputs", "カードと入力欄"),
        ["Color.Sidebar"] = new("侧边栏", "側邊欄", "Sidebar", "サイドバー"),
        ["Color.Text"] = new("正文文字", "本文文字", "Body text", "本文"),
        ["Color.Muted"] = new("辅助文字", "輔助文字", "Secondary text", "補助テキスト"),
        ["Color.Accent"] = new("强调色", "強調色", "Accent", "アクセント"),
        ["Color.Border"] = new("界面边框", "介面邊框", "UI borders", "境界線"),
        ["Color.WheelBackground"] = new("扇区底色", "扇區底色", "Sector fill", "セクター背景"),
        ["Color.WheelBorder"] = new("轮盘描边", "輪盤描邊", "Wheel border", "ホイール境界線"),
        ["Color.WheelHighlight"] = new("扇区高亮", "扇區高亮", "Sector highlight", "セクター強調色"),
        ["Color.WheelText"] = new("轮盘文字", "輪盤文字", "Wheel text", "ホイール文字"),
        ["Color.WheelHighlightText"] = new("高亮文字", "高亮文字", "Highlight text", "強調時の文字"),
        ["Invalid"] = new("请检查这些字段：", "請檢查這些欄位：", "Check these fields:", "次の項目を確認："),
        ["LowContrast"] = new("文字对比度较低，建议调整配色。", "文字對比度較低，建議調整配色。", "Low text contrast. Consider adjusting these colors.", "文字のコントラストが低いため、配色の調整をおすすめします。"),
        ["Contrast"] = new("正文 / 高亮对比度", "本文 / 高亮對比度", "Body / highlight contrast", "本文 / 強調時のコントラスト"),
        ["Saved"] = new("主题已保存并应用。", "主題已儲存並套用。", "Theme saved and applied.", "テーマを保存して適用しました。"),
        ["Applied"] = new("风格已应用。", "風格已套用。", "Style applied.", "スタイルを適用しました。"),
        ["Unsaved"] = new("修改已应用，但未能写入配置文件。请检查文件权限。", "修改已套用，但無法寫入設定檔。請檢查檔案權限。", "Applied, but the configuration could not be saved. Check file permissions.", "適用済みですが設定を保存できませんでした。ファイルの権限を確認してください。"),
        ["Imported"] = new("已导入为独立主题，点击应用即可使用。", "已匯入為獨立主題，點選套用即可使用。", "Imported as an independent theme. Apply it when ready.", "独立したテーマとして取り込みました。適用すると使用できます。"),
        ["Exported"] = new("主题文件已导出。", "主題檔案已匯出。", "Theme file exported.", "テーマファイルをエクスポートしました。"),
        ["Deleted"] = new("自定义主题已删除。", "自訂主題已刪除。", "Custom theme deleted.", "カスタムテーマを削除しました。"),
        ["FileError"] = new("无法处理主题文件：", "無法處理主題檔案：", "Could not process theme file:", "テーマファイルを処理できません："),
        ["ThemeFilter"] = new("StarPie 主题 (*.starpie-theme.json)|*.starpie-theme.json|JSON 文件 (*.json)|*.json", "StarPie 主題 (*.starpie-theme.json)|*.starpie-theme.json|JSON 檔案 (*.json)|*.json", "StarPie theme (*.starpie-theme.json)|*.starpie-theme.json|JSON files (*.json)|*.json", "StarPie テーマ (*.starpie-theme.json)|*.starpie-theme.json|JSON ファイル (*.json)|*.json"),
        ["SampleTitle"] = new("命令中心", "命令中心", "Command center", "コマンドセンター"),
        ["SampleHint"] = new("你的常用动作，随手可达。", "你的常用動作，隨手可達。", "Your actions, always within reach.", "いつもの操作を、すぐ手元に。"),
        ["SampleButton"] = new("快捷操作", "快速操作", "Quick action", "クイック操作"),
        ["Missing"] = new("所选主题无法读取，已使用纸感极简回退。", "所選主題無法讀取，已使用紙感極簡回復。", "Selected theme is unavailable. Paper is used as a fallback.", "選択したテーマを読み込めないため、ペーパーを使用しています。"),
        ["LegacyHint"] = new("整体主题开启时，下方配色用于保存原有独立轮盘设置。", "整體主題啟用時，下方配色用於保留原有獨立輪盤設定。", "With a whole-app style enabled, the controls below retain your independent wheel settings.", "全体スタイルの使用中、下の設定は従来の独立ホイール設定として保持されます。")
    };
    public static IEnumerable<string> Keys => Strings.Keys;
    public static string Get(string key) => Strings.TryGetValue(key, out var value) ? value.Get(I18n.CurrentLanguage) : key;
    public static string Name(ArtStyleProfile p) => ArtStyleCatalog.IsBuiltIn(p.Id) ? Get(p.Id) : p.Name;
}
